baseURL = "https://github.com/annabrorson/hugosite2"
languageCode = "en-us"
title = ""
theme = "osprey"
publishDir = "docs"

[[menu.main]]
name               	= "Home"
weight             	= 1
identifier         	= "home"
url                	= "/"



[[menu.main]]
name               	= "Portfolio"
weight             	= 2
identifier         	= "portfolio"
url                	= "/portfolio/"

[[menu.main]]
name               	= "Kontakt"
weight             	= 4
identifier         	= "contact"
url                	= "/contact/"

[[menu.main]]
name               	= "Blog"
weight             	= 4
identifier         	= "blog"
url                	= "/blog/"



[[menu.main]]
name               	= "Om"
weight             	= 5
identifier         	= "about"
url                	= "/about/"




