baseURL = "http://example.org/"
languageCode = "en-us"
title = ""
theme = "osprey"

[[menu.main]]
name               	= "Home"
weight             	= 1
identifier         	= "home"
url                	= "/"



[[menu.main]]
name               	= "Portfolio"
weight             	= 2
identifier         	= "portfolio"
url                	= "/portfolio/"

[[menu.main]]
name               	= "Kontakt"
weight             	= 3
identifier         	= "contact"
url                	= "/contact/"



[[menu.main]]
name               	= "Om"
weight             	= 4
identifier         	= "about"
url                	= "/about/"




