baseURL = "http://example.org/"
languageCode = "en-us"
title = "Velkommen"
theme = "osprey"

[[menu.main]]
name               	= "Home"
weight             	= 1
identifier         	= "home"
url                	= "/"

[[menu.main]]
name               	= "Blog"
weight             	= 2
identifier         	= "blog"
url                	= "/blog/"

[[menu.main]]
name               	= "Portfolio"
weight             	= 3
identifier         	= "portfolio"
url                	= "/portfolio/"

[[menu.main]]
name               	= "Contact"
weight             	= 4
identifier         	= "contact"
url                	= "/contact/"



[[menu.main]]
name               	= "About"
weight             	= 5
identifier         	= "about"
url                	= "/about/"




